# -*- coding: utf-8 -*-
"""Deliverable7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PvkkunQ77Gjg8cJvXxZzSUwGixtb9Kdo
"""

import pandas as pd

n = int(input("Enter a non-negative integer number: "))
if n < 0: print("ERROR: Please enter a valid integer.")

even = []
odd = []
fibo = [0,1]

for i in range(n):
  even.append(2*i)
  odd.append(2*i+1)
  if i > 1: fibo.append(fibo[i-2]+fibo[i-1])

odd

fibo

len(even) == len(odd) == len(fibo) #Test to check the len of the three lists

results = pd.DataFrame({'even':even, 'odd':odd, 'fibo':fibo})
results